name: Deploy ADF to Production

on:
  workflow_dispatch:  
  
  push:
    branches:
      - adf_publish

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
       - name: Checkout adf_publish
         uses: actions/checkout@v4
         with:
            ref: adf_publish
            
       - name: Debug
         run: |
           echo "Current branch:"
           git branch --show-current
      
           echo ""
           echo "Root directory:"
           pwd
      
           echo ""
           echo "Repository contents:"
           ls -la
      
           echo ""
           echo "All ARM templates:"
           find . -iname "*arm*"
      
           echo ""
           echo "All JSON files:"
           find . -iname "*.json"
